import { StyleSheet } from "react-native";

export const communStyle = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 100,
    paddingBottom: 100,
    justifyContent: "flex-start",
    // flexDirection: "column-reverse",
    alignItems: "center",
    backgroundColor: "#1a1a2e",
  },
  title: {
    color: "white",
    fontSize: 44,
    fontFamily: "Old English Text MT",
    textShadowColor: "black",
    textShadowOffset: { width: 6, height: 6 },
    shadowOpacity: 0.1,
    textTransform: "uppercase",
  },
  nottitle: {
    color: "white",
    fontSize: 30,
    fontFamily: "Old English Text MT",
    textShadowColor: "black",
    textShadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.1,
    // textTransform: "uppercase"
  },
  rotatingImage: {
    width: 150,
    height: 150,
    marginVertical: 20,
  },
  button: {
    backgroundColor: "#561d54",
    paddingHorizontal: 40,
    paddingVertical: 16,
    borderRadius: 12,
    marginTop: 20,
    borderWidth: 2,
    borderColor: "#7c127b",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 12,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    letterSpacing: 1,
  },
  container404: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1a1a2e",
    paddingHorizontal: 20,
  },
  title404: {
    fontSize: 120,
    fontWeight: "bold",
    color: "#ff6b6b",
    textShadowColor: "#000",
    textShadowOffset: { width: 4, height: 4 },
    textShadowRadius: 10,
  },
  subtitle404: {
    fontSize: 28,
    color: "#ffffff",
    fontWeight: "600",
    marginTop: 20,
    textAlign: "center",
  },
  description404: {
    fontSize: 16,
    color: "#b0b0b0",
    marginTop: 10,
    marginBottom: 30,
    textAlign: "center",
  },
  button404: {
    backgroundColor: "#ff6b6b",
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 10,
    marginTop: 20,
    borderWidth: 0,
    shadowColor: "#ff6b6b",
    elevation: 10,
  },
});
